import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faAngleDoubleDown,
  faBirthdayCake,
  faBookmark,
  faCommentAlt,
  faDizzy,
  faEdit,
  faEnvelope,
  faExclamationTriangle,
  faHeart,
  faHistory,
  faKey,
  faLocationArrow,
  faSave,
  faSearch,
  faSignOutAlt,
  faStar,
  faUser,
  faUserCog,
  faUserMinus,
  faUserPlus,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faSignOutAlt,
  faUser,
  faEdit,
  faKey,
  faLocationArrow,
  faBirthdayCake,
  faEnvelope,
  faBookmark,
  faSave,
  faUserPlus,
  faDizzy,
  faUserMinus,
  faExclamationTriangle,
  faAngleDoubleDown,
  faKey,
  faHeart,
  faStar,
  faHistory,
  faSearch,
  faUserCog,
  faCommentAlt
);
